### ISSUE TITLE
BGP loopback 7.2 and 7.0 configuration compatibility

### ISSUE THREAD

**Issue by Gubleduk** [fortinet-solutions-cse/sdwan-advpn-reference#17]
For FortiOS version 7.0.12 (without FortiManager, just text configuration files), does BGP loopback 7.2 configuration work?

**Comment by dmitryperets** [comment]
Hi, 

For FOS 7.0, you should use the branch `release/7.0`. It supports BGP on Loopback, and the offline renderer is pretty much the same. But compatibility is guaranteed by using the right branch.

**Comment by Gubleduk** [comment]
I appreciate your response.

My goal is to establish tunnels through all channels to all hubs (FullMesh) as explained in https://github.com/fortinet-solutions-cse/sdwan-advpn-reference/wiki/Advanced-Hub-connection-options: -Many-to-One-and-Full-Mesh

It is indicated here, however, that this logic is only implemented in version 7.2.

**Comment by dmitryperets** [comment]
Hi, 

Yes, unfortunately, we've added that functionality only to the 7.2 branch. 
I cannot guarantee that it will work 100% for 7.0...

**Comment by Gubleduk** [comment]
Thanks. I try
