### ISSUE TITLE
Hub multi-tenancy support

### ISSUE THREAD

**Issue by mnankeng** [fortinet-solutions-cse/sdwan-advpn-reference#27]
Hi Team,

I have implemented the design referenced in this repository. However it seems that the Hub Multitenancy feature as described in the link below is not supported by the provided jinja templates and variables.

https://docs.fortinet.com/document/fortigate/7.2.0/sd-wan-sd-branch-architecture-for-mssps/616464/blueprint-1-mssp-premises-multitenant

Am I missing anything or is it expected to be available in the future?

Thank you,

**Comment by dmitryperets** [comment]
Hi @mnankeng, you are correct. The Jinja Orchestrator doesn't take care of the multitenancy. All the VDOM management must happen outside it, using the native FortiManager tools.
