### ISSUE TITLE
Template rendering issue - HUBs with different number of ISP interfaces

### ISSUE THREAD

**Issue by mavbig** [fortinet-solutions-cse/sdwan-advpn-reference#35]
Hi Dmitry,

as mentioned in the other issue, there is a "problem" if one HUB in the template has two ISP interfaces, and another HUB has only one.
Usually I use the OneSizeFitsAll profile for the spokes, but this doesn't work if used in a region where the HUB has only one VPN endpoint interface.

Here is the profile which works fine for SPOKEs connecting to HUBs with two WAN interfaces:

```
'OneSizeFitsAll': {
  'ha': true,
  'interfaces': [
    {
      'name': isp1_interface,
      'role': 'wan',
      'ul_name': 'ISP1',
      'ol_type': 'ISP1',
      'ip': isp1_ip,
      'dia': true,
      'access': 'ping https ssh'
    },
    {
      'name': isp2_interface,
      'role': 'wan',
      'ul_name': 'ISP2',
      'ol_type': 'ISP2',
      'ip': isp2_ip,
      'dia': true,
      'access': 'ping https ssh'
    },
    {
      'name': isp3_interface,
      'role': 'wan',
      'ul_name': 'ISP3',
      'ol_type': 'ISP1',
      'ip': isp3_ip,
      'dia': true,
      'access': 'ping https ssh'
    },
    {
      'name': isp1_interface,
      'role': 'wan',
      'ul_name': 'ISP1',
      'ol_type': 'ISP2'
    },
    {
      'name': isp2_interface,
      'role': 'wan',
      'ul_name': 'ISP2',
      'ol_type': 'ISP1'
    },
    {
      'name': isp3_interface,
      'role': 'wan',
      'ul_name': 'ISP3',
      'ol_type': 'ISP2'
    }
  ]
}
```

The HUBs are configured like this:

```
{% set hubs = {

    'HUB1': {
      'lo_bgp': '172.20.1.253',
      'overlays': {
        'ISP1': {
          'wan_ip': h1_isp1,
          'network_id': '11',
          'hub2hub': false
        }
      }
    },

    'HUB2': {
      'lo_bgp': '172.20.3.253',      
      'overlays': {
        'ISP1': {
          'wan_ip': h1_isp1,
          'network_id': '21',
          'hub2hub': false
        },
        'ISP2': {
          'wan_ip': h1_isp2,
          'network_id': '22',
          'hub2hub': false
        }
      }
    }
  }
%}
```

But if I use the device profile for HUB1, it tries to create tunnels to ISP2, which is not defined for HUB1 and this generates an error.
I worked around the issue by setting up a second device profile, like this:

```
OneISPOneSizeFitsAll': {
  'ha': true,
  'interfaces': [
    {
      'name': isp1_interface,
      'role': 'wan',
      'ul_name': 'ISP1',
      'ol_type': 'ISP1',
      'ip': isp1_ip,
      'dia': true,
      'access': 'ping https ssh'
    },
    {
      'name': isp2_interface,
      'role': 'wan',
      'ul_name': 'ISP2',
      'ol_type': 'ISP1',
      'ip': isp2_ip,
      'dia': true,
      'access': 'ping https ssh'
    }
  ]
}
```

The thing is that on SPOKEs it doesn't matter if there is one, two or three internet lines, the VPNs are skipped if these interfaces are missing, but I guess this same check is not done on the HUB side, but you will probably know where this is implemented :)
It's not really an issue for me, but it would be a nice improvement, because then it would just be possible to use the device profile "OneSizeFitsAll" as a default value in the meta field, and it's one thing less to configure/worry about.

Thank you!

**Comment by dmitryperets** [comment]
Hi, 

We automatically skip the interfaces with undefined name. So, for example, if you don't set the variable `isp2_interface`, then we skip this part:

```j2
    {
      'name': isp2_interface,
      'role': 'wan',
      'ul_name': 'ISP2',
      'ol_type': 'ISP2',
      'ip': isp2_ip,
      'dia': true,
      'access': 'ping https ssh'
    }
```

However, your profile also has this:

```j2
    {
      'name': isp1_interface,
      'role': 'wan',
      'ul_name': 'ISP1',
      'ol_type': 'ISP2'
    }
```

So, because `isp1_interface` is defined, we will try to generate the Dial-Up for the `ol_type = ISP2`, and this is where the rendering fails on your HUB1. 

And the same issue exists also when we render the Spoke config. For instance, if you have a Spoke with two ISP links, then we will try to render this:

```j2
      {
         'name': isp2_interface,
         'role': 'wan',
         'ul_name': 'ISP2',
         'ol_type': 'ISP2',
         'ip': isp2_ip,
         'dia': true,
         'access': 'ping https ssh'
      }
```

So we'll try to build an ISP2 tunnel **towards each Hub**, hence again it will fail for HUB1. 

So yes, we have an assumption today that all the Hubs serving the region have the same topology and the same amount of overlays. Let me see if we can change that without breaking anything...

**Comment by dmitryperets** [comment]
Hi @mavbig, please try the `feature/ol-check-hubs` branch (from PR #37). It should automatically skip those overlays that do not exist on a particular Hub.

**Comment by mavbig** [comment]
Hi Dmitry,

this indeed fixed the issue, I deployed all FortiGates again with the new code, no problem at all - able to use one device profile now for all locations, great!

Thanks for the fast fix!
