### ISSUE TITLE
Duplicate global switches

### ISSUE THREAD

**Issue by ramakrishnanr89** [fortinet-solutions-cse/sdwan-advpn-reference#5]
These two global switches are repeated once inside the optional settings and once outside. I am not sure if this was intentionally created like this. But I feel it should only be defined once.

{% set cert_auth = true %}
{% set multireg_advpn = true %}

**Comment by dmitryperets** [comment]
Hi @ramakrishnanr89,

Note that the section with optional settings is commented (it's surrounded by `{# #}`). You don't need it, when you write your own Project template, it is not rendered anyway. I put it just as an example, to show what parameters you **can** define and show their default values when you **do not** define them. 

So for example, the default value is `set multireg_advpn = false`. So if you do not put it in the Project template, the Jinja will handle it as "false". You can see it in the 04-Hub-MultiRegion.j2, for example, here:

```
          {% if project.multireg_advpn|default(false) %}     <<<<<<<<
          set auto-discovery-sender enable
          set auto-discovery-receiver enable
          set auto-discovery-forwarder enable
          set add-route disable
          {% else %}
          set exchange-interface-ip enable
          {% endif %}
```

So this commented section is intended just to show people the default values, without them going through the Jinja and looking them up. This is also documented in the reference doc [here](https://github.com/fortinet-solutions-cse/sdwan-advpn-reference/blob/release/7.2/Project_Template_Reference.md#optional-parameters). 

What comes **after** the commented section, on the other hand, are the actual parameters for which I wanted to use a value which is NOT default. So e.g. in the provided Project template I wanted to extend ADVPN across the regions, therefore I had to explicitly do `set multireg_advpn = true`.

Hopefully this clarifies it!
